machine: M0001
card: A0001

host:
  address: 192.168.1.10
  user: user
  password: password

guest:
  address: 192.168.11.10

output_dir: ./output

driver:
  name: nic-driver
  version: 1.0.0

nic:
  vmnics: [vmnic0, vmnic1]
